apiVersion: apps/v1
kind: Deployment
metadata:
  name: drop-recovery-predictor
  namespace: "stocks"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drop-recovery-predictor
  template:
    metadata:
      labels:
        app: drop-recovery-predictor
    spec:
      containers:
      - name: drop-recovery-predictor
        image: docker.io/library/drop-recovery-predictor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: flask-database-uri
                key: DATABASE_URI
          - name: FLASK_ENV
            value: production  # Specify the environment for Flask