apiVersion: v1
kind: Service
metadata:
  name: drop-recovery-predictor-service
  namespace: "stocks"
spec:
  selector:
    app: drop-recovery-predictor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer